### PR TITLE
Hotfix Relayer fee issue

### LINKED ISSUE #4185: LowRelayerFee coming up
**Describe the bug**
Seeing some transfers not processing due to LowRelayerFee. This should be a very rare occurence.

**To Reproduce**
1. Example: https://connextscan.io/tx/0x0c24bd10199b89da24956575cd793a57386471a775ba9c2605b8751835fa624c
2. Logs link: https://app.datadoghq.com/logs?query=@requestContext.transferId:0x0c24bd10199b89da24956575cd793a57386471a775ba9c2605b8751835fa624c&cols=service&index=mainnet-production&messageDisplay=inline&saved-view-id=1285114&stream_sort=desc&viz=stream&from_ts=1683698410356&to_ts=1683712810356&live=true

**Additional context**

### PR DESCRIPTION
**Pull request by sanchaymittal**
## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## Related Issue(s)

Fixes #4185

### CODE REVIEW

File: packages/agents/sequencer/src/lib/helpers/relayerfee.ts [hunk 1]
```diff
@@ -106,7 +108,8 @@ export const canSubmitToRelayer = async (transfer: XTransfer): Promise<{ canSubm
         canonicalNativeUsd,
         canonicalAssetCanonicalNative,
       });
-      assetPriceUsd = canonicalNativeUsd === 0 ? 0 : canonicalAssetCanonicalNative / canonicalNativeUsd;
+      // get pricing of asset in USD
+      assetPriceUsd = canonicalNativeUsd === 0 ? 0 : canonicalNativeUsd / canonicalAssetCanonicalNative;
```
Comment (rhlsthrm) [inline packages/agents/sequencer/src/lib/helpers/relayerfee.ts:112]:
```suggestion
      assetPriceUsd = canonicalAssetCanonicalNative === 0 ? 0 : canonicalNativeUsd / canonicalAssetCanonicalNative;
```

**Review by rhlsthrm — CHANGES_REQUESTED** [review]

**Review by LayneHaber — APPROVED** [review]

**Review by rhlsthrm — APPROVED** [review]
