### PR TITLE
Check error context message

### LINKED ISSUE #3363: LowSlippage transfer error status not saved in DB
**Describe the bug**

Example transfer: https://connextscan.io/tx/0x93768e9fe5c6bb43f49277a2cd2b19660bd878975a34f12c6f67531a698778d3

Low slippage error:
image

Yet, `error_status` is null in DB. This causes the UI to not display the call to action for users to bump slippage.

**To Reproduce**
1. Do a transfer with high slippage
2. Wait for it to fail with error `dy < minDy`
3. Check transfer in DB, see the `error_status` is not updated

**Additional context**

### PR DESCRIPTION
**Pull request by just-a-node**
## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## Related Issue(s)

Fixes #3363

### CODE REVIEW

File: packages/adapters/relayer/src/index.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const sendWithRelayerWithBackup = async (
       return { taskId };
     } catch (err: unknown) {
       const jsonError = jsonifyError(err as NxtpError);
-      error_msg = jsonError.message;
+      error_msg = jsonError.context.message ?? jsonError.message;
```
Comment (preethamr) [inline packages/adapters/relayer/src/index.ts:75]: May be this should be:
`error_msg = jsonError.context?.message ?? jsonError.message;`

**Review by preethamr — APPROVED** [review]
Needs one quick change
